//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterials
    {
        public int ID_Order { get; set; }
        public int ID_Suppliers { get; set; }
        public string Order_Document { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
